export 'home.dart';
export 'profile.dart';
export 'settings.dart';
export 'history.dart';
export 'mygames.dart';
// export 'result_screen.dart';
export 'results.dart';
export 'game_quiz.dart';
export 'game_screen.dart';
export 'login.dart';
export 'signup.dart';
export 'loading_home_wrapper.dart';
export 'history.dart';